language: perl
arch:
 - arm64
matrix:
 include:
  - dist: xenial
    perl: 5.24
  - dist: bionic
    perl: 5.26
  - dist: focal
    perl: 5.32
  - dist: focal
    perl: 5.32
    env: USE_SYSTEM_PERL=1

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq xvfb twm
 - '[ "$USE_SYSTEM_PERL"  = "1" ] && perlbrew off || true'
 - '[ "$USE_SYSTEM_PERL" != "1" ] && sudo apt-get install -qq libx11-dev libfreetype6-dev libxft-dev || true'
 - Xvfb :123 &
 - export DISPLAY=:123
 - (sleep 10; twm) &
install:
 - '[ "$USE_SYSTEM_PERL"  = "1" ] && sudo apt-get install -qq perl-tk libxml-parser-perl || true'
 - '[ "$USE_SYSTEM_PERL" != "1" ] && cpanm --quiet --notest --installdeps . || true'

branches:
 except:
  - /appveyor/
  - /github-actions/
  - /doozer/
